api/urls.py
from django.urls import path
from api import views


app_name = 'api'

urlpatterns = [
    path('search_products/', views.search_product, name='search_products'),
    path('purchases/', views.purchases, name='purchases'),
    path('shopping-list/', views.shoppinglist, name='shopping-list'),
    path('change_count_product/', views.change_count_product, name='change_count_product'),
    path('make_order/', views.make_order, name='make_order'),
    path('to_order_call/', views.to_order_call, name='to_order_call'),
    path('get_subcategory_products/', views.get_subcategory_products, name='get_subcategory_products')
]

krd_samogon/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'online_store.views.page_not_found'
handler500 = 'online_store.views.server_error'

urlpatterns = [
    path('Zanin/FlowHack/admin-panel-KrDsAmOgOnUrAl/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include('api.urls')),
    path('user/', include('users.urls')),
    path('', include('online_store.urls', namespace='online_store'))
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

online_store/urls.py
from django.urls import path

from online_store import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:id_category>/', views.category, name='category'),
    path('product/<int:id_product>', views.product, name='product'),
    path(
        'subcategory/<int:id_subcategory>', views.subcategory,
        name='subcategory'
    ),
    path('shoplist/', views.shop_list, name='shop_list'),
    path('orders/', views.orders, name='orders'),
    path('payment/', views.payment, name='payment')
]

templates/main/cookies.html
<section class="u-align-center u-clearfix u-cookies-consent u-grey-80 u-cookies-consent" id="sec-05e8">
  <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
    <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
      <div class="u-gutter-0 u-layout">
        <div class="u-layout-row">
          <div class="u-container-style u-layout-cell u-left-cell u-size-43-md u-size-43-sm u-size-43-xs u-size-46-lg u-size-46-xl u-layout-cell-1">
            <div class="u-container-layout u-valign-top-lg u-valign-top-md u-valign-top-xl u-container-layout-1">
              <h3 class="u-align-center-sm u-align-center-xs u-text u-text-1">Cookies &amp; Privacy</h3>
              <p class="u-text u-text-2">Этот сайт использует Cookies файлы для ускорения его работы.</p>
            </div>
          </div>
          <div class="u-align-left u-container-style u-layout-cell u-right-cell u-size-14-lg u-size-14-xl u-size-17-md u-size-17-sm u-size-17-xs u-layout-cell-2">
            <div class="u-container-layout u-valign-middle-lg u-valign-middle-md u-valign-middle-sm u-container-layout-2">
              <a href="###" class="u-border-2 u-border-black u-btn u-button-confirm u-button-style u-hover-black u-none u-text-black u-btn-1">Принять</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <style>
    .u-cookies-consent {
      background-image: none;
    }

    .u-cookies-consent .u-sheet-1 {
      min-height: 172px;
    }

    .u-cookies-consent .u-layout-wrap-1 {
      margin-top: 10px;
      margin-bottom: 10px;
    }

    .u-cookies-consent .u-layout-cell-1 {
      min-height: 152px;
    }

    .u-cookies-consent .u-container-layout-1 {
      padding: 30px 60px;
    }

    .u-cookies-consent .u-text-1 {
      font-size: 1.875rem;
      margin: 0 516px 0 0;
    }

    .u-cookies-consent .u-text-2 {
      font-size: 1rem;
      margin: 4px 158px 0 0;
    }

    .u-cookies-consent .u-layout-cell-2 {
      min-height: 152px;
    }

    .u-cookies-consent .u-container-layout-2 {
      padding: 30px 29px 30px 30px;
    }

    .u-cookies-consent .u-btn-1 {
      font-size: 1rem;
      margin: 27px auto 0 0;
      padding: 5px 63px 6px;
    }

    @media (max-width: 1199px) {
      .u-cookies-consent .u-sheet-1 {
        min-height: 131px;
      }

      .u-cookies-consent .u-layout-cell-1 {
        min-height: 125px;
      }

      .u-cookies-consent .u-text-1 {
        margin-right: 362px;
      }

      .u-cookies-consent .u-text-2 {
        margin-right: 5px;
      }

      .u-cookies-consent .u-layout-cell-2 {
        min-height: 126px;
      }

      .u-cookies-consent .u-container-layout-2 {
        padding-left: 9px;
        padding-right: 9px;
      }

      .u-cookies-consent .u-btn-1 {
        margin-top: 0;
        margin-left: auto;
        padding-right: 47px;
        padding-bottom: 6px;
        padding-left: 45px;
      }
    }

    @media (max-width: 991px) {
      .u-cookies-consent .u-sheet-1 {
        min-height: 106px;
      }

      .u-cookies-consent .u-layout-cell-1 {
        min-height: 100px;
      }

      .u-cookies-consent .u-container-layout-1 {
        padding-left: 30px;
        padding-right: 30px;
      }

      .u-cookies-consent .u-text-1 {
        margin-right: 217px;
      }

      .u-cookies-consent .u-text-2 {
        font-size: 0.875rem;
        margin-right: 0;
      }

      .u-cookies-consent .u-layout-cell-2 {
        min-height: 100px;
      }
    }

    @media (max-width: 767px) {
      .u-cookies-consent .u-sheet-1 {
        min-height: 174px;
      }

      .u-cookies-consent .u-layout-wrap-1 {
        margin-top: 1px;
        margin-bottom: 1px;
      }

      .u-cookies-consent .u-layout-cell-1 {
        min-height: 105px;
      }

      .u-cookies-consent .u-container-layout-1 {
        padding-right: 0;
        padding-bottom: 20px;
        padding-left: 10px;
      }

      .u-cookies-consent .u-text-1 {
        width: 303px;
        margin-left: auto;
        margin-right: auto;
      }

      .u-cookies-consent .u-text-2 {
        width: auto;
        margin-top: 0;
        margin-left: 50px;
        margin-right: 50px;
      }

      .u-cookies-consent .u-layout-cell-2 {
        min-height: 65px;
      }

      .u-cookies-consent .u-container-layout-2 {
        padding-top: 10px;
        padding-bottom: 10px;
      }
    }

    @media (max-width: 575px) {
      .u-cookies-consent .u-sheet-1 {
        min-height: 172px;
      }

      .u-cookies-consent .u-layout-wrap-1 {
        margin-top: 10px;
        margin-bottom: 10px;
      }

      .u-cookies-consent .u-layout-cell-1 {
        min-height: 152px;
      }

      .u-cookies-consent .u-container-layout-1 {
        padding-bottom: 30px;
        padding-left: 60px;
        padding-right: 60px;
      }

      .u-cookies-consent .u-text-1 {
        margin-right: 516px;
        margin-left: 0;
        width: auto;
      }

      .u-cookies-consent .u-text-2 {
        margin-top: 4px;
        margin-right: 158px;
        margin-left: 0;
        width: auto;
      }

      .u-cookies-consent .u-layout-cell-2 {
        min-height: 152px;
      }

      .u-cookies-consent .u-container-layout-2 {
        padding: 30px 29px 30px 30px;
      }

      .u-cookies-consent .u-btn-1 {
        margin-top: 27px;
        margin-left: 0;
        padding-right: 63px;
        padding-bottom: 6px;
        padding-left: 63px;
      }
    }
  </style>
</section>

templates/main/footer.html
{% load static %}
{% load user_tags %}
{% get_year as year %}

<section class="footer">
  <footer>
    <div class="footer-img">
      <img src="{% static 'images/logo.png' %}">
    </div>
    <div class="content-footer">
      <a href="#" style="text-decoration: none">
        <span style="color: yellow">Заказать звонок:&nbsp;</span>+7(861) 290-02-50
      </a><br>
      <a href="https://wapp.click/79282053255" style="text-decoration: none">
        <span style="color: yellow">What`s app:</span>&nbsp;+7(928) 205-32-55
      </a>
      <hr class="hr-footer" style="color: white;">
      <p class="text-center text-muted">
        &copy; 2021-{{ year }} Created by <a href="https://github.com/FlowHack" style="text-decoration: none">FlowHack</a>
      </p>
    </div>
  </footer>
</section>

templates/main/header.html
{% load static %}
{% load user_tags %}
{% get_categories as categories %}

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'online_store:index' %}">
      <img id="what_replace_when_order_call-header" src="{% static 'images/favicon.jpg' %}" alt="" width="35" class="brand-img-header"">
      <div class="spinner_for_call" id="spinner_for_call-header">
        <div class="spinner-grow text-warning" role="status"><span class="visually-hidden">Загрузка...</span></div>
      </div>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page">
            {% if user.is_authenticated %}Здравствуйте, {{ request.user.first_name }}!{% else %}Здравствуйте!{% endif %}
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Категории
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            {% for category in categories %}
            <li><a class="dropdown-item" href="{% url 'online_store:category' id_category=category.id %}">{{ category.title }}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Контакты
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Доставка</a></li>
            <li><a class="dropdown-item" href="{% url 'online_store:payment' %}">Оплата</a></li>
            <li><a class="dropdown-item" href="#">Контакты</a></li>
            <li><hr class="dropdown-divider"></li>
            {% if user.is_authenticated %}
            <li style="cursor: pointer"><a id="header_to_order_call" on_what_replace_id="spinner_for_call-header" what_replace_id="what_replace_when_order_call-header" need_replace="true" class="dropdown-item" onclick="to_order_call('header_to_order_call')">Заказать звонок</a></li>
            {% endif %}
            <li><a class="dropdown-item" target="_blank" href="https://wapp.click/79282053255">What`s app</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Кабинет
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'online_store:orders' %}">Заказы</a></li>
            <li><a class="dropdown-item" href="{% url 'online_store:shop_list' %}">Корзина</a></li>
            <li><hr class="dropdown-divider"></li>
            {% if user.is_authenticated and request.user.is_staff %}
            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ панель</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="{% url 'password_reset' %}">Cменить пароль</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Выход</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'login' %}">Вход</a></li>
            <li><a class="dropdown-item" href="{% url 'signup' %}">Регистрация</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input id="search" class="search form-control me-2 bg-dark" onKeyUp="showHint(this.value)" placeholder="Поиск товара">
      </form>
    </div>
  </div>
</nav>
<div class="hint" id="hint_search"></div>