api/urls.py
from django.urls import path
from api import views


app_name = 'api'

urlpatterns = [
    path('search_products/', views.search_product, name='search_products'),
    path('purchases/', views.purchases, name='purchases'),
    path('shopping-list/', views.shoppinglist, name='shopping-list'),
    path('change_count_product/', views.change_count_product, name='change_count_product'),
    path('make_order/', views.make_order, name='make_order'),
    path('to_order_call/', views.to_order_call, name='to_order_call'),
    path('get_subcategory_products/', views.get_subcategory_products, name='get_subcategory_products')
]

krd_samogon/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'online_store.views.page_not_found'
handler500 = 'online_store.views.server_error'

urlpatterns = [
    path('Zanin/FlowHack/admin-panel-KrDsAmOgOnUrAl/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include('api.urls')),
    path('user/', include('users.urls')),
    path('', include('online_store.urls', namespace='online_store'))
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

online_store/urls.py
from django.urls import path

from online_store import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:id_category>/', views.category, name='category'),
    path('product/<int:id_product>', views.product, name='product'),
    path(
        'subcategory/<int:id_subcategory>', views.subcategory,
        name='subcategory'
    ),
    path('shoplist/', views.shop_list, name='shop_list'),
    path('orders/', views.orders, name='orders'),
    path('payment/', views.payment, name='payment')
]

templates/includes/card_category.html
{% load static %}

<div class="col">
  <div class="card-content card h-100 border-secondary">
    {% if category.image.url %}
    <a href="{% if view_category %}{% url 'online_store:category' id_category=category.id %}{% else %}{% url 'online_store:subcategory' id_subcategory=category.id %}{% endif %}">
      <img src="{{ MEDIA_URL }}{{ category.image.url }}" class="card-img card-img-top">
    </a>
    {% elif product.preview_image.url %}
    <a href="{% url 'online_store:product' id_product=product.id %}">
      <img src="{{ MEDIA_URL }}{{ product.preview_image.url }}" class="card-img card-img-top">
    </a>
    {% else %}
    <a href="{% if view_category %}{% url 'online_store:category' id_category=category.id %}{% elif view_product %}{% url 'online_store:product' id_product=product.id %}{% else %}{% url 'online_store:subcategory' id_subcategory=category.id %}{% endif %}">
      <img src="{% static 'images/product.jpeg' %}" class="card-img card-img-top">
    </a>
    {% endif %}
    <div class="card-body" style="padding: 0;">
      <h5 class="title_card card-title" align="center">{{ category.title }}{{ product.title }}</h5>
    </div>
    {% if not view_product %}
    <div class="list-group">
      {% if view_category %}
      {% for subcategory in category.in_subcategories.all|slice:":4" %}
      <a href="{% url 'online_store:subcategory' id_subcategory=subcategory.id %}" class="li_card list-group-item list-group-item-action">
        {% if subcategory.title|length > 17 %}
        {{ subcategory.title|slice:":17" }}...
        {% else %}
        {{ subcategory.title }}
        {% endif %}
      </a>
      {% empty %}
      <a class="li_card list-group-item list-group-item-action disabled">Нет подкатегорий</a>
      {% endfor %}
      {% else %}
      {% for product in category.in_products.all|slice:":4" %}
      <a href="{% url 'online_store:product' id_product=product.id %}" class="li_card list-group-item list-group-item-action">
        {% if product.title|length > 17 %}
        {{ product.title|slice:":17" }}...
        {% else %}
        {{ product.title }}
        {% endif %}
      </a>
      {% empty %}
      <a class="li_card list-group-item list-group-item-action disabled">Нет товаров</a>
      {% endfor %}
      {% endif %}
    </div>
    {% else %}
    <ul class="list-group list-group-flush">
      <li align="center" class="characteristic-li list-group-item">₽ {{ product.price }}</li>
    </ul>
    <hr style="margin: 0">
    {% endif %}
    <div class="card-body">
      <a href="{% if view_category %}{% url 'online_store:category' id_category=category.id %}{% elif view_product %}{% url 'online_store:product' id_product=product.id %}{% else %}{% url 'online_store:subcategory' id_subcategory=category.id %}{% endif %}" type="button" class="btn_card btn-center btn btn-outline-dark">Перейти</a>
    </div>
  </div>
</div>

templates/includes/card_order.html
{% load user_tags %}

<div class="accordion_style accordion-item">
  <p class="accordion-header" id="flush-heading{{ order.id }}">
    <button style="display: block;" class="btn-collapsed accordion-button collapsed" type="button"data-bs-toggle="collapse" data-bs-target="#flush-collapse{{ order.id }}" aria-expanded="false"  aria-controls="flush-collapse{{ order.id }}">
      <h5 class="title_accordion-item">{{ title }} {{ date }}</h5>
      <p class="description-accordion-item">Количество товаров: {{ order|count_items_int_order }}<br>На сумму {{order|total_cost_order }}₽</p>
    </button>
  </p>
  <div id="flush-collapse{{ order.id }}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{ order.id }}" data-bs-parent="#accordionFlushExample">
    <div class="accordion-body">
      <div class="list-group">
        {% for item in order.items.all %}
        <a href="{% url 'online_store:product' id_product=item.product.id %}"
           class="characteristic-li list-group-item list-group-item-action">{{ item.product.title }} | {{ item.quantity}}шт. | {{ item.product.price }}₽</a>
        {% endfor %}
      </div>
    </div>
  </div>
</div>